org :
  neo4j :
    driver :
      uri : bolt://localhost:7687
      authentication :
        username : neo4j
        password : password
database : neo4j
spring :
  graphql :
    graphiql :
      enabled : true