@startuml

[*] -right-> creating

creating -right-> editing : create

editing --> editing : save
editing --> team_reviewing : submit
team_reviewing --> dept_reviewing : submit

dept_reviewing -right-> tracking : approve

team_reviewing --> editing : reject
dept_reviewing -right-> team_reviewing : reject
dept_reviewing -[#red,dashed]-> editing : reject

tracking -down-> tracking : track
tracking --> [*] : close

@enduml